 # This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Product.create!(name: 'Вомер', body: 'х/к', shops: 'Сумской рынок', category_id: 4)
Product.create!(name: 'Голець', body: 'х/к с/г УВРК',	shops: 'Сумской рынок',category_id: 4)
Product.create!(name: 'Горбуша х/к б/г УВРК, кг.',	shops: 'Сумской рынок',category_id: 4 )
Product.create!(name: 'Кальмар філе х/к "КІТ"', shops: 'Сумской рынок', category_id: 4 )
Product.create!(name: 'Карп г/к	' ,shops: 'Сумской рынок', 	category_id: 3)
Product.create!(name: 'Лещ г/к	', shops: 'Сумской рынок' ,	category_id: 3)
Product.create!(name: 'Лосось филе х/к	 ', shops: 'Сумской рынок',	category_id: 4)
Product.create!(name: 'Масляная х/к филе	', shops: 'Сумской рынок', 	category_id: 4)
Product.create!(name: 'Набор к пиву х/к 	', shops: 'Сумской рынок', category_id: 4)
Product.create!(name: 'Окунь г/к ' ,shops: 'Сумской рынок',	 category_id: 3)
Product.create!(name: 'Окунь г/к б/г, УВРК патран. Mosrkoy	', category_id: 3)
Product.create!(name: 'Осетр филе х/к	 ',	 category_id: 4)
Product.create!(name: 'Палтус спинка х/к УВРК, кг.	', category_id: 4)
Product.create!(name: 'Сайра г/к УВРК, кг.	', category_id: 3)
Product.create!(name: 'Сайра х/к "КІТ", УВРК	', category_id: 4)
Product.create!(name: 'Скумбрия г/к б/г УВРК	', 	 category_id: 3)
Product.create!(name: 'Скумбрія г/к с/г УВРК, кг.	', category_id: 3)
Product.create!(name: 'Скумбрія х/к б/г УВРК, кг.	', category_id: 4)
Product.create!(name: 'Скумбрія х/к с/г, УВРК +дейнеко',	 category_id: 4)
Product.create!(name: 'Сом филе х/к', category_id: 4)
Product.create!(name: 'Ставрида г/к Кит',	 category_id: 3)
Product.create!(name: 'Судак г/к',	 category_id: 3)
Product.create!(name: 'Толстолоб г/к',	 	category_id: 3)
Product.create!(name: 'Толстолоб филе х/к',	 	 category_id: 4)
Product.create!(name: 'Тунец филе х/к',	 	category_id: 4)
Product.create!(name: 'Форель филе',	 	category_id: 3)
Product.create!(name: 'Щука',		 	 category_id: 3)
Product.create!(name: 'барабулька',	 	 	 category_id: 3)
Product.create!(name: 'кинг-клип',	 category_id: 3)
Product.create!(name: 'мойва',  	category_id: 3)
Product.create!(name: 'Окунь',  	category_id: 3)
Product.create!(name: 'окунь речной',  	category_id: 3)
Product.create!(name: 'сибас, дорадо',	 	 category_id: 3)
Product.create!(name: 'скумбрия', 	 	 category_id: 3)
Product.create!(name: 'скумбрия сголовой' ,	category_id: 3)
Product.create!(name:  'хек', 	category_id: 3)

Product.create!(name:  'Ассорти с лосося с/с',	 	price: 98.90, category_id: 6) 	
Product.create!(name:  'Брюшки лосося с/с	 '	, 	price: 	 89.75,	 	category_id: 6) 
Product.create!(name:  'Иваси с/с	',	 	price:  69.60,	 	 	category_id: 6) 
Product.create!(name:  'Килька пряного пос. Прибалтійська	',	 	price:  42.00 , category_id: 6) 
Product.create!(name:  'Лосось филе с/с 	',	 	price: 689.90,	 	category_id: 6) 
Product.create!(name:  'Мидии с/с	 ',	 	price: 	 200.00,	 	category_id: 6) 
Product.create!(name:  'Оселедець 300+ с/с, кг.	 ',	 	price: 	 59.00,	 	category_id: 6) 
Product.create!(name:  'Оселедець філе с/с в/уп., кг. ',	 	price: 	 134.40, category_id: 6) 
Product.create!(name:  'Пивной набор с лосося с/с	 ',	price: 	 200.00,	 	category_id: 6) 
Product.create!(name:  'Селедка кусочки  с/с в масле	 ', 	price: 	 90.00, category_id: 6) 
Product.create!(name:  'Селедка кусочки  с/спо мексикански	 	', price:  90.00, category_id: 6) 
Product.create!(name:  'Селелка дунайская с/с	 ', price: 	 170.00, category_id: 6) 
Product.create!(name:  'Сельдь матиас 	 	', price:  110.00, category_id: 6) 
Product.create!(name:  'Скумбрія філе с/с в/уп., кг.	',	 	price:  129.60, category_id: 6) 
Product.create!(name:  'Скуммбрия в масле (кусочки) ОТ Полеж.',	 	price:  100.00, category_id: 6) 
Product.create!(name:  'Форель филе с/с, кг.	'	, 	price: 689.90,	 	category_id: 6) 
Product.create!(name:  'Хамса провисная с/с	 	'	, 	price:  75.00,	 	category_id: 6) 
Product.create!(name:  'Скумбрия кусочки с/с по мексикански	 	',	 	price:  100.00,	 	category_id: 6) 
Product.create!(name:  'Лосось нарізка с/с в упак.	 	',	 	price:  750.00,	 	category_id: 6) 
Product.create!(name:  'Форель нарізка с/с в упак.	 	', price:  750.00,	 	category_id: 6) 
Product.create!(name:  'Шматочки оселед.в олії в бан.	 	', price:  30.00, category_id: 6) 
Product.create!(name:  'Шматочки оселед.в олії з пряност. в бан.', price:  30.00, category_id: 6) 
Product.create!(name:  'Икра горбуши 	 	 ', price: 2400.00, category_id: 8) 
Product.create!(name:  'Икра кеты 	 	',	 	price:  2350.00	 ,	category_id: 6) 
Product.create!(name:  'Икра кижуч 	 	',	 	price:  2650.00	, 	category_id: 6) 
Product.create!(name:  'Икра нерки	 	'	, 	price:  2400.00	, 	category_id: 8)  
Product.create!(name:  'Икра щуки 	 	'	, 	price:  1500.00	, 	category_id: 8) 
Product.create!(name:  'Икра мойвы УВРК	 '	, 	price: 	 350.00	 ,	category_id: 6) 
Product.create!(name:  'Икра стерляди	 	'	, 	price:  25000.00	, 	category_id: 6) 
Product.create!(name:  'Икра кеты 32	 	'	, 	price:  2450.00,	 	category_id: 6) 
Product.create!(name:  'Икра кеты +	 	'	, 	price:  2550.00	, 	category_id: 6) 
Product.create!(name:  'икра нерки(роман)	 	'	, 	price:  2600.00	, 	category_id: 6) 
Product.create!(name:  'Икра горбуши завод	 	',	 	price:  2500.00	 ,	category_id: 6) 
Product.create!(name:  'Икра горбуши брак.	 	'	, 	price:  2550.00	 ,	category_id: 8) 
Product.create!(name:  'Икра кеты брак.	 	'	 ,	price:  2600.00	 ,	category_id: 8) 
Product.create!(name:  'Икра кета крупная	 '	 ,	price: 	 2750.00	, 	category_id: 8) 
Product.create!(name:  'Икра горбуша сухая	 	'	, 	price:  2600.00	 ,	category_id: 8) 
Product.create!(name:  'Икра кета Дельфин	 '	 ,	price: 	 2700.00	, category_id: 8) 	
Product.create!(name:  'Икра кеты Курилы	 	'	, 	price:  3300.00	, 	category_id: 8) 
Product.create!(name:  'Крабовые палочки 0,240 г'	, 	price:	 	 30.00,	 	 category_id: 13) 
Product.create!(name:  'Крабовые палочки 0,500 г'	 ,	price:	 	 60.00	, 	category_id: 13) 
Product.create!(name:  'Крабовые палочки (весовые)'	 ,	price:	 	 110.00	, 	category_id: 13) 
Product.create!(name:  'Бестер'	, 	price:	 	 	 0,	category_id: 2)
Product.create!(name:  'Голець'	 ,	price: 	 	  	 	0,category_id: 2)	 	
Product.create!(name:  'Калкан'	 ,	price:	 	 	 	 0,	 	category_id: 2)
Product.create!(name:  'Лосось'	 ,	price:	 	 300.00	 ,	 	 	category_id: 2)
Product.create!(name:  'Нерка'	 ,	price:	 	 500.00	 ,	 	 	category_id: 2)
Product.create!(name:  'Осетр'	 ,	price:	 	 300.00	 	, 	 	category_id: 2)
Product.create!(name:  'Сибас 800-100',	 	price:	 	 300.00	 ,	 	 	category_id: 2)
Product.create!(name:  'Форель'	 	,price:	 	 350.00	 	 ,	 	category_id: 2)
Product.create!(name:  'Форель 2-3'	 ,	price:	 	 300.00	 	, 	 	category_id: 2)
Product.create!(name:  'Білий Амур, кг.',	 	price: 80.00	, 	 	 	category_id: 2)
Product.create!(name:  'Карась, кг.',	 	price: 30.00	 ,	 	 	category_id: 2)
Product.create!(name:  'Карп 1-2',	 	price: 50.00	 	 ,	 	category_id: 2)
Product.create!(name:  'Кижуч'	 ,	price: 300.00	 	 	, 	category_id: 2)
Product.create!(name:  'Линь'	 ,	price: 80.00	 	 ,	 	category_id: 2)
Product.create!(name:  'Пеленгас',	 	price: 80.00	 ,	 	 	category_id: 2)
Product.create!(name:  'Пеленгас мелкий(кефаль)	',	 	price: 	77 	 	, 	 	category_id: 2)
Product.create!(name:  'Сазан, кг.	',	 	price: 5.00	 ,	 	 	category_id: 2)
Product.create!(name:  'сом 1-3 кг	 ',	 	price:	 80.00	, 	 	 	category_id: 2)
Product.create!(name:  'Сом 5-10+	',	 	price: 120.00	, 	 	 	category_id: 2)
Product.create!(name:  'Судак великий	 ',	 	price:  120.00	, 	 	 	category_id: 2)
Product.create!(name:  ' Судак средний	',	 	price:	 	 0	, 	category_id: 2)
Product.create!(name:  ' Товстолоб 5-10 кг',	 	price: 50.00,	 	 	 	category_id: 2)
Product.create!(name:  'Толстолоб 10+',	 	price:	 55.00	  	 ,	category_id: 2)	
Product.create!(name:  ' Щука велика',	 	price:	 	 80.00	 ,	 	 	category_id: 2)
Product.create!(name:  ' Белый амур стейк',	 	price:	 	 150.00,	 	 	 	category_id: 2)
 Product.create!(name:  'Икра',	 	price:	 	 100.00	, 	 	 	category_id: 2)
Product.create!(name:  'Лосось стейк',	 	price:	 	 370.00,	 	 	 	category_id: 2)
Product.create!(name:  ' Лосось филе'	, 	price:		 	 	 	0	,category_id: 2)
Product.create!(name:  ' Мясо осетра(белуга)',	 	price:		 	 750.00	, 	 	 	category_id: 2)
Product.create!(name:  'Обрезки с лосося '	, 	price:		 	 39.75,	 	 	 	category_id: 2)
Product.create!(name:  ' осетр голова	'	, 	price:	 	 200.00	 ,	 	 	category_id: 2)
Product.create!(name:  ' Осетр стейк	'	, 	price:	 	 850.00	 ,	 	 	category_id: 2)
Product.create!(name:  ' Пеленгас стейк	'	, 	price:	 	 	 0,	 	 	category_id: 2)
Product.create!(name:  ' Сазан стейк, кг.	',	 	price:	 	 150.00	 ,	 	 	category_id: 2)
Product.create!(name:  ' Сом голова	 '	 ,	price:		 20.00	, 	 	 	category_id: 2)
Product.create!(name:  'Сом стейк	'	, 	price:	 	 250.00	 	, 	 	category_id: 2)
Product.create!(name:  ' Суповой набор излосося и форели	',	 	price:	 	 50.00	 	, 	 	category_id: 2)
Product.create!(name:  'Толстолоб стейк	'	 ,	price:	 	 120.00	 	 ,	 	category_id: 2)
Product.create!(name:  'Толстолоб филе'	 ,	price:		 	 150.00	 	 ,	 	category_id: 2)
Product.create!(name:  'Форель стейк',	 	price:		 	 430.00	, 	category_id: 2)
Product.create!(name:  'Гребешок 40*50'	, 	price:		 	 755.00	, 	 	 	category_id: 9)
Product.create!(name:  'Морской гребешок 10*70'	, 	price:		 	 1000.00,		category_id: 9) 	
Product.create!(name:  'Морской гребешок 20*40	',	 	price:	 	 825.00	, 		category_id: 9)
Product.create!(name:  'Морской гребешок 120*150',	 	price:		 	 550.00,	 		category_id: 9)
Product.create!(name:  'Клешни крабов сырые	'	 ,	price:	 	 1500.00,	 		category_id: 11)
 Product.create!(name:  'Клешни крабов варен.(щупальца)	 ',	 	price:		 1500.00,	category_id: 11) 	
 Product.create!(name:  'Краб клешни А', 	price:		 	 1000.00,	 	category_id: 11)
 Product.create!(name:  'Краб клешни синие	',	 	price:	 	 1500.00,	 	category_id: 11)
 Product.create!(name:  'Краб клешни Я	 ',	 	price:		 1000.00,	 	category_id: 11)
 Product.create!(name:  'Краб целый (варен)',	 	price:		 	 1800.00,	 	category_id: 11)
 Product.create!(name:  'Краб целый (морож)	',	 	price:	 	 1800.00,	 	category_id: 11)
 Product.create!(name:  'Креветка 100-130 манец	 '	, 	price:		 270.00,	 	category_id: 10)
 Product.create!(name:  'Креветка 120-150 манец	 ',	 	price:		 280.00,	 	category_id: 10)
 Product.create!(name:  'Креветка 40/60 вареная одиссей', price:	 	 630.00,	 	category_id: 10)
 Product.create!(name:  'Креветка 51-60 королевская манец',	 	price:		 	 375.00,	category_id: 10) 	
 Product.create!(name:  'Креветка 70-90 гренландия	',	 	price:	 	 360.00,	 	category_id: 10)
 Product.create!(name:  'Креветка 80-100 гренландия	 '	, 	price:		 350.00	, 	category_id: 10)
 Product.create!(name:  'Креветка 90-120 гренландия	'	, 	price:	 	 310.00,	 	category_id: 10)
 Product.create!(name:  ' Креветка 90-120 манец	 '	, 	price:		 320.00,	 	category_id: 10)
 Product.create!(name:  'Креветка Polar seafood  коктейльная',	 	price:		 	 375.00,	 	category_id: 10)
 Product.create!(name:'Креветка Polar seafood  с головой 16*20	',	 	price:	 	 500.00,	 	category_id: 10)
 Product.create!(name:'Креветка Polar seafood б/г 16*20	 ',	 	price:		 570.00,	 	category_id: 10)
 Product.create!(name:'Креветка Polar seafood чищенная+тигр вар чищ хвост 31/40',	 	price:		 525, category_id: 10)	 	
 Product.create!(name:'Креветка ботан вар.мор. Весовая	 ',	 	price:		 1300.00,	 	category_id: 10)
 Product.create!(name:'Креветка ботан свеж-мор.	 ',	 price:		 1300.00,	 	category_id: 10)
 Product.create!(name:'Креветка медведка	 ',	 	price:		 1200.00,	category_id: 10) 	
 Product.create!(name:'Креветка тигр. с гол (одиссей) 16/20	 ',	 	price:		 850.00,	 	category_id: 10)
 Product.create!(name:'Креветка тигр.чищ.хвосты вар.мор. Весовая	 '	, 	price:		 450.00,	 	category_id: 10)
 Product.create!(name:'Креветка тигровая 6-8 одиссей	 ',	 	price:		 1600.00,	 	category_id: 10)
 Product.create!(name:'Креветка тигровая скандинавия с/м ',	 	price:		 	 500.00,	 	category_id: 10)
 Product.create!(name:'Креветка углехвостая	',	 	price:		 500.00,	 category_id: 10)
 Product.create!(name:'Креветка ХХХL(Вана мей)',	 	price:		 300.00,	 	category_id: 10)
 Product.create!(name:'Креветка черноморская',	 	price:		 300,	 	category_id: 10)
 Product.create!(name:'Креветка черноморская мелкая	 ',	 	price:		 200.00	, 	category_id: 10)
 Product.create!(name:'Креветка чищен МГМ	 ',	 	price:		 300.00,	 	category_id: 10)
 Product.create!(name:'Лагнустин	 ',	 	price:		 510.00,	 	category_id: 10)
 Product.create!(name:'Мидии полуракушка Нов.Зел',	 	price:		 	 375.00,	 	category_id: 9)
 Product.create!(name:'Мидии полуракушка чили	',	 	price:	 	 275.00,	 	category_id: 9)
 Product.create!(name:'Мясо краба	',	 	price:	 	 2700.00,	 	category_id: 11)
 Product.create!(name:'Мясо краба в глазури	',	 	price:	 	 2500.00,	category_id: 11) 	
 Product.create!(name:'Мясо рапана	 ',	 	price:		 160.00,	 	category_id: 9)
 Product.create!(name:'Осьминог 1/2	',	 	price:	 	 810.00,	 	category_id: 9)
 Product.create!(name:'Раки 60-90	',	 	price:	 	 500.00	, 	category_id: 1)
 Product.create!(name:'Раки 90+	 ',	 	price:		 600.00,	 	category_id: 1)
 Product.create!(name:'Раки средние 40-60	',	 	price:	 	 400.00	, 	category_id: 1)
 Product.create!(name:'Устрицы 4 Seasons №2 4 сезона	',	 	price:	 	 60.00,	 	category_id: 9)
 Product.create!(name:'Устрицы Ostra Regal №2	',	 	price:	 	 90.00,	 	category_id: 9)
 Product.create!(name:'Устрицы Speciales №2	',	 	price:	 	 45.00	, 	category_id: 9)
 Product.create!(name:'Устрицы Tia-Maraa №2	',	 	price:	 	 95.00	, 	category_id: 9)

 Product.create!(name:'Акула(морской кролик)	',	 	price:	 	 105.00	, 	category_id: 2)
 Product.create!(name:'Блувайтинг тушка 100-250	'	, 	price:	 	 85.00	, 	category_id: 2)
 Product.create!(name:'Бычки '	, 	price:		 	 25.00	 ,	category_id: 2)
 Product.create!(name:'Кальмар Россия',	 	price:		 	 200.00	, 	category_id: 9)
 Product.create!(name:'Кальмар-тубы(Манец)	',	 	price:	 	 160.00	 ,	category_id: 9)
 Product.create!(name:'Камбала б/г	'	 ,	price:	 	 100.00	, 	category_id: 2)
 Product.create!(name:'Килька с/м',	 	price:		 	 15.00	, 	category_id: 2)
 Product.create!(name:'Кинг-клип',	 	price:		 	 160.00	, 	category_id: 2)
 Product.create!(name:'Кита стейк	',	 	price:	 	 275.00	 ,	category_id: 2)
 Product.create!(name:'Масляная стейк(Манец)',	 	price:	0,	 	 	 	category_id: 2)
 Product.create!(name:'Мидии (манец)	',	 	price:	 	 165.00,	 	category_id: 9)
 Product.create!(name:'Мойва с/м	 '	, 	price:		0, 	 	category_id: 2)
 Product.create!(name:'Морской коктель	 '	, 	price:		 130.00	, 	category_id: 2)
 Product.create!(name:'Натотения-тушка	 '	, 	price:		 67.00,	 	category_id: 2)
 Product.create!(name:'Окунь красный б/г	'	, 	price:	 	 170.00,	 	category_id: 2)
 Product.create!(name:'Окунь красный б/г 500-700	',	 	price:	 	 170.00,	 	category_id: 2)
 Product.create!(name:'Осьминожки-беби	 ',	 	price:		 215.00	, 	category_id: 9)
 Product.create!(name:'Пангасиус тушка	',	 	price:	 	 	 	0, category_id: 2)
 Product.create!(name:'Пикша	',	 	price:	 	 160.00	, 	category_id: 2)
 Product.create!(name:'скумбрия с/г7400-600 (манец) исландия',	 	price:		0, category_id: 2)	
 Product.create!(name:'Стейк акулы	',	 	price:	 	 83.50,	 	category_id: 2)
 Product.create!(name:'Стейк зубатки	',	 	price:	 	 62.00,	 	category_id: 2)
 Product.create!(name:'Треска красная б/г 350-750(манец)	',	 	price:	 	 100.00, category_id: 2)	 	
 Product.create!(name:'Треска крупная(мурманск)	'	, 	price:	 	 350.00	, 	category_id: 2)
 Product.create!(name:'Тунец красный филе с/м	',	 	price:	 	 650.00	, 	category_id: 2)
 Product.create!(name:'Тунец-(сериола-тушка)	',	 	price:	 	 120.00	, 	category_id: 2)
 Product.create!(name:'Филе минтая б/ш (манец)	',	 	price:	 	 75.00,	 	category_id: 2)
 Product.create!(name:'Филе окуня красного с/м	',	 	price:	 	 135.00	, 	category_id: 2)
 Product.create!(name:'Филе пангасиуса(манец)	 '	, 	price:		 85.00	, 	category_id: 2)
 Product.create!(name:'Филе тилапии б/ш (манец)	 '	, 	price:		 130.00	 ,	category_id: 2)
 Product.create!(name:'Филе трески (Мурманск)	'	, 	price:	 	 350.00	, 	category_id: 2)
 Product.create!(name:'Филе трески(Архангельск)'	, 	price:		 	 420.00	 ,	category_id: 2)
 Product.create!(name:'Филе хека б/ш (Манец)'	, 	price:		 	 82.00	, 	category_id: 2)
 Product.create!(name:'Филе хека с/ш(Манец)	'	, 	price:	 	 82.00,	 	category_id: 2)
 Product.create!(name:'Филе хека(аргентина)	'	, 	price:	 	 150.00	, 	category_id: 2)
 Product.create!(name:'Хек-тушка  канада 200-400	'	, 	price:	 	 80.00	 ,	category_id: 2)
 Product.create!(name:'Хек-тушка 200-400 розовый'	, 	price:		 	 75.00	, 	category_id: 2)
 Product.create!(name:'Хек-тушка 300-500 сух заморозка	 ',	 	price:		 75.00,	 	category_id: 2)
 Product.create!(name:'Хек-тушка валастро иберкон.'	, 	price:		 	 92.00,	 	category_id: 2)
 Product.create!(name:'Тунец сриблястий'	, 	price:		 	 347.00,	 	category_id: 2)
 Product.create!(name:'Бички сушені з перцем, кг.'	, 	price:		 	 180.20	, 	category_id: 14)
 Product.create!(name:'Быч. тушка сол-суш.	'	, 	price:	 	 221.20,	 	category_id: 14)
 Product.create!(name:'Восьминіг солоно-сушений, кг.',	 	price:		  330.40,	 	category_id: 14)
 Product.create!(name:'Кальмар в арах масле	'	, 	price:	 	 386.40,	 	category_id: 14)
 Product.create!(name:'Кальмар кольца сол-суш.'	 ,	price:		 	 287.00	 ,	category_id: 14)
 Product.create!(name:'Кальмар стружка	 ',	 	price:		 399.00	 ,	category_id: 14)
 Product.create!(name:'Лосось соломка(палочка)	'	, 	price:	 	 329.00	, 	category_id: 14)
 Product.create!(name:'Лосось стружка',	 	price:		 	 385.00,	 	category_id: 14)
 Product.create!(name:'Соломка воблы',	 	price:		 	 375.00	, 	category_id: 14)
 Product.create!(name:'Соломка сазана в паприке	 ',	 	price:		 450.00	, 	category_id: 14)
 Product.create!(name:'Соломка сома	',	 	price:	 	 450.00,	 	category_id: 14)
 Product.create!(name:'Соломка щуки касп.',	 	price:		 	 450.00	, 	category_id: 14)
 Product.create!(name:'Соломка щуки касп. (острая)	',	 	price:	 	 500.00	, 	category_id: 14)
 Product.create!(name:'Спинка тріски, кг.',	 	price:		 308.00	, 	category_id: 14)
 Product.create!(name:'Ставридка'	, 	price:		 359.35	, 	category_id: 14)
 Product.create!(name:'Стейк леща	',	 	price:	 	 250.00	, 	category_id: 14)
 Product.create!(name:'Треска с перцем	',	 	price:	 	 359.35	, 	category_id: 14)
 Product.create!(name:'Форель соломка'	, 	price:		 	 322.00,	 	category_id: 14)
 Product.create!(name:'Чипсы карася ',	 	price: 450.00	, 	category_id: 14)
 Product.create!(name:'Чипсы лосося ',	 	price: 500.00	 ,	category_id: 14)
 Product.create!(name:'Чипсы сазана острые ',	 	price: 500.00,	 	category_id: 14)
 Product.create!(name:'Чипсы щуки касп ',	 	price: 500.00	, 	category_id: 14)
 Product.create!(name:'Чипсы щуки острые '	, 	price:  500.00	, 	category_id: 14)
 Product.create!(name:'Янтарна з перцем, кг. ',	 	price: 287.00,	 	category_id: 14)
 Product.create!(name:'Солока білого амура ',	 	price: 470.00,	 	category_id: 14)
 Product.create!(name:'Солока тарані ',	 	price: 385.00,	 	category_id: 14)
 Product.create!(name:'Бычки вял ',	 	price: 120.00	 	,category_id: 14)
 Product.create!(name:'Вобла с икрой крупная ',	 	price:  0,	 	 	category_id: 14)
 Product.create!(name:'Вобла с икрой мелкая ',	 	price: 49.95,	 	 	category_id: 14)
 Product.create!(name:'Вобла с икрой средняя ',	 	price: 500.00,	 	category_id: 14)
 Product.create!(name:'Вобла с икрой супер ',	 	price: 750.00	, 	category_id: 14)
 Product.create!(name:'Жерех . ',	 price: 250.00	 	,category_id: 14)
 Product.create!(name:'Камбала  з ікрой,кг ',	 	price: 600.00	 	,category_id: 14)
 Product.create!(name:'Камбала ерш	 	 450.00 ',	 	price: 	0 	,category_id: 14)
 Product.create!(name:'орюшка  без икры ',	 	price: 750.00	, 	category_id: 14)
 Product.create!(name:'Корюшка з ікрою вял., кг. '	, 	price: 	850.00,	 	category_id: 14)
 Product.create!(name:'Кутум '	, 	price: 	 	 200,category_id: 14)
 Product.create!(name:'Лещ вял чищ с икрой '	, 	price: 200.00	 	,category_id: 14)
 Product.create!(name:'Лещ каспийский с икрой '	 ,	price: 200.00	 	,category_id: 14)
 Product.create!(name:'Лящ  чищений, кг. '	, 	price: 100.00	 	,category_id: 14)
 Product.create!(name:'Окунь , кг. '	, 	price: 125.00	 ,	category_id: 14)
 Product.create!(name:'Плотва чищ. з ікрою, кг. ',	 	price: 250.00	 ,	category_id: 14)
 Product.create!(name:'Плотва чищенная '	, 	price:  100.00	 ,	category_id: 14)
 Product.create!(name:'Ряпушка,кг.	 ',	 	price:  125.75	 ,	category_id: 14)
 Product.create!(name:'Себель(верховодка)'	 ,	price: 	 	 150.00	 ,	category_id: 14)
 Product.create!(name:'Синець чищений с икрой	'	, 	price:  89.60	 	 	,category_id: 14)
 Product.create!(name:'Судак , кг.	',	 	price: 200.00	 	,category_id: 14)
 Product.create!(name:'Судак чищенный	 	'	, 	price:  	 	0,category_id: 14)
 Product.create!(name:'Тарань  чищена с икрой',	 	price:  350.00	, 	category_id: 14)
 Product.create!(name:'Тарань вяленая с икрой',	 	price: 	 	 	0, 	category_id: 14)
 Product.create!(name:'Тарань чищ без икры	',	 	price:  	 150.00	, 	category_id: 14)
 Product.create!(name:'Чехонь  чищена, кг.'	, 	price: 	 260.00	, 	 	category_id: 14)
 Product.create!(name:'Щука Каспийская	 ',	 	price: 	 450.00	 ,						category_id: 14) 
 Product.create!(name:'Корюшка без икры старая	',	 	price:  	 375.00,	 	category_id: 14)
 Product.create!(name:'Каперсы	 	 46.00	 '	, 	price: 46.00,	category_id: 13)
 Product.create!(name:'Килька в т/с Вентспилс	'	, 	price:  	 30.00,	 	category_id: 13)
 Product.create!(name:'Конерва икра осетра 0,100 гр	',	 	price:  	 3900.00	, 	category_id: 13)
 Product.create!(name:'Консаерва скумбрия спецзаказ	'	, 	price:  	 42.00,	 	category_id: 13)
 Product.create!(name:'Консерва  гребешок русский берег	',	 	price:  	 330.00	, 	category_id: 13)
 Product.create!(name:'Консерва  тунец Galvo',	 	price: 	 	 30.00	, 	category_id: 13)
 Product.create!(name:'Консерва Br.villnis шпроты 0,160	'	, 	price:  	 45.00	, 	category_id: 13)
 Product.create!(name:'Консерва Br.villnis шпроты 0,190	 '	, 	price: 	 60.00	, 	category_id: 13)
 Product.create!(name:'Консерва Br.villnisкилька	'	, 	price:  	 45.00	, 	category_id: 13)
 Product.create!(name:'Консерва KAIJA лосось и тунец'	, 	price: 	 	 67.00	, 	category_id: 13)
 Product.create!(name:'Консерва Tacos'	, 	price: 	 	 35.00,	 	category_id: 13)
 Product.create!(name:'Консерва белуга, осетр, севрюга'	, 	price: 	 	 235.00	, 	category_id: 13)
 Product.create!(name:'Консерва восточный берег горбуша',	 	price: 	 	 345.00	,category_id: 13) 	
 Product.create!(name:'Консерва горбуши	 ',	 	price: 	 55.00,	 	category_id: 13)
 Product.create!(name:'Консерва гребешок стекло	'	, 	price:  	 473.00	 ,	category_id: 13)
 Product.create!(name:'Консерва иваси доброфлот 0,240',	 	price: 	 	 60.00	 ,	category_id: 13)
 Product.create!(name:'Консерва иваси доброфлот бол.',	 	price: 	 300.00,	 	category_id: 13)
 Product.create!(name:'Консерва икра  нерки в стекле 0,550 гр.'	, 	price: 	 	 825.00	, 	category_id: 13)
 Product.create!(name:'Консерва иваси магелан прянка',	 	price: 	180.00	, 	category_id: 13)
 Product.create!(name:'Консерва икра Жемчужина Сахалина	 '	, 	price:	 350.00	, 	category_id: 13)
 Product.create!(name:'Консерва икра нерки в стекле 0,230 гр.	',	 	price: 	 540.00	, 	category_id: 13)
 Product.create!(name:'Консерва икра нерки в стекле 0,600 гр	',	 	price: 	 1425.00,	 	category_id: 13)
 Product.create!(name:'Консерва икра осетра 0,50 гр	',	 	price: 	 2000.00,	 	category_id: 13)
 Product.create!(name:'Консерва икра палтуса черная	 '	, 	price:	 165.00	, 	category_id: 13)
 Product.create!(name:'Консерва икра парсах	 ',	 	price:	 365.00	, 	category_id: 13)
 Product.create!(name:'Консерва икра рыбная	 ',	 	price:	 33.00	 ,	category_id: 13)
 Product.create!(name:'Консерва икра сига	',	 	price: 	 50.00	 	,category_id: 13)
 Product.create!(name:'Консерва икра Сик кета',	 	price:	 	 345.00	 	,category_id: 13)
 Product.create!(name:'Консерва икра трески	 ',	 	price:	 33.00	 ,	category_id: 13)
 Product.create!(name:'Консерва икра тунайча	',	 	price: 	 270.00	 	,category_id: 13)
 Product.create!(name:'Консерва икра черная Горпунов',	 	price:	 	 3900.00	, 	category_id: 13)
 Product.create!(name:'Консерва икра щука лемберг	',	 	price: 	 195.00	 	,category_id: 13)
 Product.create!(name:'Консерва икра щуки атраханской',	 	price:	 	 200.00	 ,	category_id: 13)
 Product.create!(name:'Консерва кальмар без кожи	',	 	price: 	 60.00	 ,	category_id: 13)
 Product.create!(name:'Консерва кальмар(Львов)	',	 	price: 	 35.00	 	,category_id: 13)
 Product.create!(name:'Консерва кета',	 	price:	 	 60.00	 ,	category_id: 13)
 Product.create!(name:'Консерва кижуч	',	 	price: 	 66.00	 ,	category_id: 13)
 Product.create!(name:'Консерва килька Kaja	',	 	price: 	 40.00	 ,	category_id: 13)
 Product.create!(name:'Консерва килька в томате	',	 	price: 	 38.00	, 	category_id: 13)
 Product.create!(name:'Консерва килька в томате Латвия	 ',	 	price:	 30.00,	 	 category_id: 13)
 Product.create!(name:'Консерва клешни краба	',	 	price: 	 110.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва краб в жел.банке',	 	price:	 	 480.00	, 	 category_id: 13)
 Product.create!(name:'Консерва крабы( Испания)	',	 	price: 	 135.00	, 	 category_id: 13)
 Product.create!(name:'Консерва креветка (Испания)	 ',	 	price:	 135.00,	 	 category_id: 13)
 Product.create!(name:'Консерва креветка чищ. Русский берег',	price: 	 120.00	, 	 category_id: 13)
 Product.create!(name:'Консерва мускун', price:		 	 150.00	, 	 category_id: 13)
 Product.create!(name:'Консерва мясо криля Аквамарин',	 	price:	 	 68.00,	 	 category_id: 13)
 Product.create!(name:'Консерва нерка	 	 70.00	',	 	price: 0,	 category_id: 13)
 Product.create!(name:'Консерва омуль	 	 140.00	 '	, 	price:	 0,category_id: 13)
 Product.create!(name:'Консерва осетр от Константина',	 	price:	 	 235.00,	 	 category_id: 13)
 Product.create!(name:'Консерва паштет лосося	',	 	price: 	 58.00	, 	 category_id: 13)
 Product.create!(name:'Консерва паштет тунца	'	, 	price: 	 58.00,	 	 category_id: 13)
 Product.create!(name:'Консерва печ треск.Baltik Sea	'	, 	price: 	 80.00,	 	 category_id: 13)
 Product.create!(name:'Консерва печент трески золотая	 '	, 	price:	 135.00,	 	 category_id: 13)
 Product.create!(name:'Консерва печенть трески в стекле 0,350	'	, 	price: 	 335.00	, 	 category_id: 13)
 Product.create!(name:'Консерва печень и икра минтая Камчатка	'	, 	price: 	 70.00,	 	 category_id: 13)
 Product.create!(name:'Консерва печень трески "восх.ком."',	 	price:	 	 100.00,	 	 category_id: 13)
 Product.create!(name:'Консерва печень трески баренцев	 ',	 	price:	 100.00,	 	 category_id: 13)
 Product.create!(name:'Консерва печень трески желтая(константин)',	 	price:	 	 135.00,	 	 category_id: 13)
 Product.create!(name:'Консерва печень трески Мурманск 0,700 в стекле'	 ,	price:	 	 490.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва печень трески(Карелия)	 	 130.00	'	, 	price: 	0, category_id: 13)
 Product.create!(name:'Консерва печнь трески Мурманск 0,500 в стекле'	, 	price:	 	 495.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва подорочный набор'	 ,	price:	 	 1250.00	, 	 category_id: 13)
 Product.create!(name:'Консерва РЗ паштет шпротный	',	 	price: 	 17.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва РЗ шпроты 0,160	'	 ,	price: 	 41.00,	 	 category_id: 13)
 Product.create!(name:'Консерва РЗ шпроты 0,240	'	, 	price: 	 52.00	, 	 category_id: 13)
 Product.create!(name:'Консерва РКЗ Salmonica'	 ,	price:	 	 325.00	, 	 category_id: 13)
 Product.create!(name:'Консерва рыба игла'	 ,	price:	 	 100.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва рыбное меню в масле',	 	price:	 	 45.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва рыбное меню в томате',	 	price:	 	 48.00	, 	 category_id: 13)
 Product.create!(name:'Консерва ряпушка	',	 shops: 'Сумской рынок',	price: 	 90.00,	 	 category_id: 13)
 Product.create!(name:'Консерва савлат из мяса краба',	 shops: 'Сумской рынок',	price: 	 57.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва сайра Доброфлот в/м	',	 shops: 'Сумской рынок',	price: 	 60.00	 	 ,category_id: 13)
 Product.create!(name:'Консерва сайра Доброфлот нат',	 shops: 'Сумской рынок'	,price:	 	 58.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва сайра Крабик в масле',	shops: 'Сумской рынок' ,	price:	 	 65.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва сайра натур'	, shops: 'Сумской рынок',	price:	 	 60.00	 	, category_id: 13)
 Product.create!(name:'Консерва салат с кальмаров'	, shops: 'Сумской рынок',	price:	 	 60.00,	 	 category_id: 13)
 Product.create!(name:'Консерва севрюга окно',	 	shops: 'Сумской рынок',price:	 	 285.00,	 	 category_id: 13)
 Product.create!(name:'Консерва Сиг'	, 	shops: 'Сумской рынок',price: 	 	 154.00	 	 ,category_id: 13)
 Product.create!(name:'Консерва тунец  спецзаказ',	shops: 'Сумской рынок', 	price:	 	 54.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва тунец Girasol',	 shops: 'Сумской рынок',	price:	 	 300.00	 	 ,category_id: 13)
 Product.create!(name:'Консерва тунец Hacendaro',shops: 'Сумской рынок',	 	price:	 	 35.00	, 	 category_id: 13)
 Product.create!(name:'Консерва тунец NIXE'	, shops: 'Сумской рынок',	price:	 	 65.00	 	 ,category_id: 13)
 Product.create!(name:'Консерва тунец РИО 0,800 г'	, shops: 'Сумской рынок',	price:	 	 42.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва тунец Рио в с/с 0,160 гр',	 shops: 'Сумской рынок',	price:	 	 90.00,	 	 category_id: 13)
 Product.create!(name:'Консерва тунец тонно	',	 	shops: 'Сумской рынок', price: 	 42.00	 	 ,category_id: 13)
 Product.create!(name:'Консерва угорь в желе'	, shops: 'Сумской рынок',	price:	 	 600.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва филе скумбрии'	 ,	shops: 'Сумской рынок',price:	 	 90.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва чавыча Lemberd'	, 	shops: 'Сумской рынок',price:	 	 150.00	 ,	 category_id: 13)
 Product.create!(name:'Консерва шпроты 0,170 г.	',	 shops: 'Сумской рынок',	price: 	 40.00	 	 ,category_id: 13)
 Product.create!(name:'Консерва шпроты 0,170г. по 35'	,shops: 'Сумской рынок', 	price:	 	 35.00	, 	 category_id: 13)
 Product.create!(name:'Консерва шпроты в стекле'	, shops: 'Сумской рынок',	price:	 	 55.00,	 	 category_id: 13)
 Product.create!(name:'КонсерваСайра 5 морей в масле',	 shops: 'Сумской рынок',	price:	 	 45.00,	 	 category_id: 13)
 Product.create!(name:'Консервы осьминог стекло',	 shops: 'Сумской рынок',	price:	 	 110.00	 ,	 category_id: 13)
 Product.create!(name: 'Краб в стекле'	, 	shops: 'Сумской рынок', price:	 	 3300.00	 	 ,category_id: 13)
 Product.create!(name:  ' Краб в стекле 0,220 г'	,shops: 'Сумской рынок', 	price:	 	 560.00	 ,	 category_id: 13)
 Product.create!(name:  ' Краб в стекле 0,33',	 shops: 'Сумской рынок',	price:	 	 1150.00	 	 ,category_id: 13)
 Product.create!(name:  ' Краб в стекле 0,390 г',	 shops: 'Сумской рынок',	price:	 	 1120.00	 	 ,category_id: 13)
 Product.create!(name:  ' 	Краб в стекле 0,5'	, shops: 'Сумской рынок',	price:	 	 1680.00	 	 ,category_id: 13)
 Product.create!(name:  ' 	Краб в стекле 0,600	'	, shops: 'Сумской рынок',	price: 	 2400.00	 	 ,category_id: 13)
 Product.create!(name:  ' 	Краб в стекле0,700 г',	 shops: 'Сумской рынок',	price:	 	 2450.00	 	, category_id: 13)
 Product.create!(name:  ' 	 Майонез hellmanns  0.420'	, shops: 'Сумской рынок',	price:	 	 60.00,	 	 category_id: 13)
 Product.create!(name:  ' 	Майонез hellmanns 0,420',	 shops: 'Сумской рынок',	price:	 	 75.00	 ,	 category_id: 13)
 Product.create!(name:  ' 	Майонез hellmanns б'	, 	shops: 'Сумской рынок',price:	 	 115.00	 ,	 category_id: 13)
 Product.create!(name:  ' 	Масло виноградное'	 ,	shops: 'Сумской рынок',price:	 	 220.00	 	, category_id: 13)
 Product.create!(name:  ' 	Масло кунжут'	, shops: 'Сумской рынок',	price:	 	 210.00	 ,	 category_id: 13)
 Product.create!(name:  ' 	 Масло оливк нефильтр.',	 shops: 'Сумской рынок',	price:	 	 305.00	 ,	 category_id: 13)
 Product.create!(name:  ' 	 Оливки',	 shops: 'Сумской рынок',	price: 	 	 155.00	 ,	 category_id: 13)
 Product.create!(name:  ' 	Сардина в/м Вентспилс',	 shops: 'Сумской рынок',	price:	 	 33.00	 	, category_id: 13)
 Product.create!(name:  ' 	Скумбрия в/м Вентспилс'	, shops: 'Сумской рынок'	,price:	 	 36.00	, 		 	  category_id: 13)	
 Product.create!(name:  ' 	Соусы kania'	, shops: 'Сумской рынок'	,price:	 	 48.00	 ,	 category_id: 13)
 Product.create!(name:  ' 	Краб в стекле 0,430 г.',	 shops: 'Сумской рынок',	price:	 	 1275	, 	 	 category_id: 13)
 Product.create!(name:  'Икра мойвы №1 с копчен.лососем',	 shops: 'Сумской рынок'	,price:	 	 50.00	 ,	 category_id: 13)
 Product.create!(name:  ' Икра мойвы №1 с  креветкй',	 	shops: 'Сумской рынок', price:	 	 50.00	 ,	 category_id: 13)
 Product.create!(name:  'Паста икорная Икринка 0,150 с крилем'	, shops: 'Сумской рынок'	,price:	 	 30.00	, 	 category_id: 13)
 Product.create!(name:  ' Икра минтая 0,130',	 shops: 'Сумской рынок'	,price:	 	 51.00	 ,	 category_id: 13)
 Product.create!(name:  ' Икра минтая 0,90 г',	 shops: 'Сумской рынок',	price:	 	 32.00	, 	 category_id: 13)
 Product.create!(name:  ' Икра трески 0,130',	shops: 'Сумской рынок', 	price:	 	 42.00,	 	 category_id: 13)
 Product.create!(name:  ' Икра трески 0,90',	 shops: 'Сумской рынок',	price:	 	 31.00,	 	 category_id: 13)
 Product.create!(name:  ' Паста из мор.прод Антартик-Криль  классич',	shops: 'Сумской рынок', 	price:	 	 38.00,	  category_id: 13)	
 Product.create!(name:  ' Паста из мор.прод Антартик-Криль  подкоп'	, shops: 'Сумской рынок',	price:	 	 38.00,	 	 category_id: 13)
 Product.create!(name:  ' Паста из мор.прод Антартик-Криль  в слив.чесн.',	 shops: 'Сумской рынок',	price:	 	 38.00 ,category_id: 13)	 	
 Product.create!(name:  'Салат Чука с имбирем',	 shops: 'Сумской рынок'	,price:	 	 47.00	, 	 category_id: 13)
 Product.create!(name:  'Салат Чука с орехов.соусом'	, shops: 'Сумской рынок',	price:	 	 47.00	, 	 category_id: 13)
 Product.create!(name:  ' Морская капуста марин. 0,150',	 shops: 'Сумской рынок',	price:12.00,	 category_id: 13) 	
 Product.create!(name:  'Морская капуста по-корейски.0,150'	, shops: 'Сумской рынок',	price:  13.00	 ,	 category_id: 13)
 Product.create!(name:  'Морская капуста марин. 0,250'	, 	 shops: 'Сумской рынок', price:	 	 19.00,	 	 category_id: 13)
 Product.create!(name:  'Морская капуста по-корейски.',	 	price: 0.250, shops: 'Сумской рынок', category_id: 13 )
 Product.create!(name:  'Барабулька г/к	 ',	 price:	149.00	,	 category_id: 3) 	
 Product.create!(name:  'Вомер х/к (Нептун+дейнеко)',	 price:	119.85,	 category_id: 3)
 Product.create!(name:  'Кальмар філе х/к'	,price:	 273.00	 	 ,	 category_id: 4)
 Product.create!(name:  'Горбуша х/к б/г UFC',		price:	 242.50	 	 ,	 category_id: 4)
 Product.create!(name:  'Лосось філе х/к	'	,price:	 700.00	 	 ,	 category_id: 4)
 Product.create!(name:  'Лосось черевця х/к', price:	 123.50	 	 ,	 category_id: 4)
 Product.create!(name:  'Лящ г/к'	, price:	0.00	 	 ,	 category_id: 3)
 Product.create!(name:  'Мойва х/к	',price:	 84.50	 	 ,	 category_id: 4)
 Product.create!(name:  'Набір до пива лосося х/к',	price:	 260.00	 	 ,	 category_id: 3)
 Product.create!(name:  'Окунь г/к '	, price:	100.00	 	 ,	 category_id: 3)
 Product.create!(name:  'Окунь г/к б/г патр.UFC	',price:	 244.60	 	 ,	 category_id: 3)
 Product.create!(name:  'Оселедець х/к'	,price:	 85.00	 	 ,	 category_id: 4)
 Product.create!(name:  'Сайра г/к  UFC	' ,price:	168.55	 	 ,	 category_id: 4)
 Product.create!(name:  'Сайра х/к  UFC	' ,price:	114.35	 	 ,	 category_id: 4)
 Product.create!(name:  'Салака х/к UFC	' ,price:	76.05	 	 ,	 category_id: 4)
 Product.create!(name:  'Скубрия х/к с/г  UFC'	,price:	 125.50	 	 ,	 category_id: 4)
 Product.create!(name:  'Скумбрия х/к с/г(Нептун)'	, price:	0.00	 	 ,	 category_id: 4)
 Product.create!(name:  'Скумбрія г/к б/г UFC'	,price:	 185.00	 	 ,	 category_id: 3)
 Product.create!(name:  'Скумбрія г/к с/г UFC'	,price:	 157.10	 	 ,	 category_id: 3)
 Product.create!(name:  'Скумбрія х/к б/г(Нептун)'	,price:	 127.45	 	 ,	 category_id: 4)
 Product.create!(name:  'Скумбрія х/к с/г	',price:	 0.00	 	 ,	 category_id: 4)
 Product.create!(name:  'Скумрия х/к б/г UFC'	,price:	 172.00	 	 ,	 category_id: 4)
 Product.create!(name:  'Ставрида г/к (Кіт) ', price:		 131.10	 	 ,	 category_id: 3)
 Product.create!(name:  'Судак г/к	' ,price:	100.00	 	 ,	 category_id: 3)
 Product.create!(name:  'Товстолоб г/к	' ,price:	126.00	 	 ,	 category_id: 3)
 Product.create!(name:  'Товстолоб філе х/к',	 price:	210.00	 	 ,	 category_id: 4)
 Product.create!(name:  'Скумбрія х/к з/г',price:	 94.90	 	 ,	 category_id: 4)
 Product.create!(name:  'Короп г/к	',price:	 100.00	 	 ,	 category_id: 3)
 Product.create!(name:  'Щука г/к'	,price:	 100.00	 	 ,	 category_id: 3)
 Product.create!(name:  'Мясо лосося на хребті х/к	', price:	80.00	 	 ,	 category_id: 4)
 Product.create!(name:  ' Філе оселед.х/к	',price:	 150.00	 	 ,	 category_id: 4)
 Product.create!(name:  'Киперсы скумбрии х\к	',price:	 250.00	 ,	 category_id: 4)	
 Product.create!(name:  'Асорті з форелі с/с в  упак.	', price:	 102.90	 	 ,	 category_id: 6)
 Product.create!(name:  'Кілька пряного посолу (Прибалтика)	',price:	 40.30	 	 ,	 category_id: 6)
 Product.create!(name:  'Лосось філе с/с	',price:	 589.90	 	 ,	 category_id: 6)
 Product.create!(name:  'Лосось черевця сол.	' ,price:	89.75	 	 ,	 category_id: 6)
 Product.create!(name:  'Мідії с/с	', price:	 159.90	 	 ,	 category_id: 6)
 Product.create!(name:  'Молоки та ікра с/с',	price:	 25.00	 	 ,	 category_id: 6)
 Product.create!(name:  'Оселедець  великий с/с',  	price:	 0.00	 	 ,	 category_id: 6)
 Product.create!(name:  'Оселедець 400+(Ісландія)',	price:	 0.00	 	 ,	 category_id: 6)
 Product.create!(name:  'Оселедець пряного посолу',	price:	 0.00	 	 ,	 category_id: 6)
 Product.create!(name:  'Пивний набір із лосося с/с',	price:	 200.00	 	,	 category_id: 6)
 Product.create!(name:  'Скумбрия с/с с/г',	price:	 81.00	 	 ,	 category_id: 6)
 Product.create!(name:  'Форель філе с/с',	price:	 589.90	 	,	 category_id: 6)
 Product.create!(name:  'Хамса с/с', 	price:	 68.90	 	 ,	 category_id: 6)
 Product.create!(name:  'Оселедець в олії',	price:	 0.00	 	,	 category_id: 6)
 Product.create!(name:  'Оселедець шматочки  с/с по мексиканськи',	price:	 70.00	 ,	 category_id: 6)	
 Product.create!(name:  'Оселедець пряного посолу ',price:		 0.00	 	,	 category_id: 6)
 Product.create!(name:  'Оселедець філе с/с в упак.',	 price:	119.90	 	,	 category_id: 6)
 Product.create!(name:  'Оселедець с/с(акція)',	 price:	44.90	 	,	 category_id: 6)
 Product.create!(name:  'Скумбрия філе с/с в упак.',	price:	 160.00	 	,	 category_id: 6)
 Product.create!(name:  'Оселедець  шматочки с/с в олії',	price:	 70.00	 	,	 category_id: 6)
 Product.create!(name:  'Лосось нарізка с/с в упак.',	price:	 750.00	 	,	 category_id: 6)
 Product.create!(name:  'Форель нарізка с/с в упак.',	 price:	750.00	 	,	 category_id: 6)
 Product.create!(name:  'Шматочки оселед.в олії в бан.',	 price:		 30.00	 	,	 category_id: 6)
 Product.create!(name:  'Шматочки оселед.в олії з пряност. в бан.',	 price:		 30.00	 ,	 category_id: 6)	
 Product.create!(name:  'Тюлька CC	 ',	 price:	21.00	,	 category_id: 6)
 Product.create!(name:  'Морська капуста Ламінарія',	 price:		 32.40	 	,	 category_id: 6)
 Product.create!(name:  'Гриб Древесний (ваговий)',	 price:		 37.80	 	,	 category_id: 6)
 Product.create!(name:  'Капуста квашена з морквою	',	 price:	 20.25	 	,	 category_id: 6)
 Product.create!(name:  'Морква по-корейські (вагова)	',	 price:	 25.65	 	,	 category_id: 6)
 Product.create!(name:  'Огірок солений(ваговий)	',	 price:	 39.15	 	,	 category_id: 6)
 Product.create!(name:  'Салат "Хан-Хо"	 ',	 price:	29.70	 	,	 category_id: 6)
 Product.create!(name:  'Помідори червоні солоні',	 price:		 28.35	 	,	 category_id: 6)
 Product.create!(name:  'Білий амур',	 price:		 65.00	 	,	 category_id: 2)
 Product.create!(name:  'Густера',	 price:		 15.00	 	,	 category_id: 2)
 Product.create!(name:  'Дорадо 400-600',	 price:		 220.00	 	,	 category_id: 2)
 Product.create!(name:  'Дорадо 600-800	',	 price:	 250.00	 	,	 category_id: 2)
 Product.create!(name:  'Жерех',	 price:		 60.00	 	,	 category_id: 2)
 Product.create!(name:  'Піленгас дрібний',	 price:		 30.00	 	,	 category_id: 2)
 Product.create!(name:  'Короп охол.', price:		 49.90	 	,	 category_id: 2)
 Product.create!(name:  'Короп живий',	 price:		 59.90	 	,	 category_id: 2)
 Product.create!(name:  'Лин',	 price:		 70.00	 	,	 category_id: 2)
 Product.create!(name:  'Лящ',	 price:		 20.00	 	,	 category_id: 2)
 Product.create!(name:  'Лящ великий',	 price:		 30.00	 	,	 category_id: 2)
 Product.create!(name:  'Окунь ',	 price:		 45.00	 	,	 category_id: 2)
 Product.create!(name:  'Піленгас',	 price:		 60.00	 	,	 category_id: 2)
 Product.create!(name:  'Плотва',	 price:		 20.00	 	,	 category_id: 2)
 Product.create!(name:  'Рак прісноводний',	 price:		 199.00	 	,	 category_id: 2)
 Product.create!(name:  'Сазан'	, price:		 65.00	 	,	 category_id: 2)
 Product.create!(name:  'Сібас 400-600'	 ,price:		 220.00	 	,	 category_id: 2)
 Product.create!(name:  'Сібас 600-800	',	 price:	 250.00	 	,	 category_id: 2)
 Product.create!(name:  'Сом	',	 price:	 75.00	 	,	 category_id: 2)
 Product.create!(name:  'Судак великий',	 price:		 110.00	 	,	 category_id: 2)
 Product.create!(name:  'Судак дрібний	',	 price:	 80.00	 	,	 category_id: 2)
 Product.create!(name:  ' Товстолоб великий	',	 price:	 40.00	 	,	 category_id: 2)
 Product.create!(name:  'Товстолоб дрібний	',	 price:	 26.00	 	,	 category_id: 2)
 Product.create!(name:  'Товстолоб середній	',	 price:	 33.00	 	,	 category_id: 2)
 Product.create!(name:  'Короп акція	',	 price:	 39.90	 	,	 category_id: 2)
 Product.create!(name:  'Карась дрібний	',	 price:	 12.00	 	,	 category_id: 2)
 Product.create!(name:  'Щука велика	',	 price:	 80.00	 	,	 category_id: 2)
 Product.create!(name:  'Щука дрібна	',	 price:	 60.00	 	,	 category_id: 2)
 Product.create!(name:  'Карась'	, price:		 25.00	 	,	 category_id: 2)
 Product.create!(name:  'Товстолоб(акція)'	, price:		 21.90	 	,	 category_id: 2)
 Product.create!(name:  ' Лосось охолоджений'	, price:		 300.00	 	,	 category_id: 2)
 Product.create!(name:  'Піленгас великий',	 price:		 80.00	 	,	 category_id: 2)
 Product.create!(name:  'Білий амур стейк	',	 price:	 99.90	 	,	 category_id: 2)
 Product.create!(name:  'Білий амур філе	',	 price:	 131.90	 	,	 category_id: 2)
 Product.create!(name:  'Ікра',	 price:		 100.00	 	,	 category_id: 2)
 Product.create!(name:  ' Карась чищ.патр.',	 price:		 29.90	 	,	 category_id: 2)
 Product.create!(name:  'Короп чищ.патр.',	 price:		 54.90	 	,	 category_id: 2)
 Product.create!(name:  'Суповий набір з лосося і форелі	',	 price:	 50.00	 	,	 category_id: 2)
 Product.create!(name:  'Лосось стейк	',	 price:	 360.00	 	,	 category_id: 2)
 Product.create!(name:  'Лосось філе	'	, price:	 559.90	 	,	 category_id: 2)
 Product.create!(name:  'Лосось прихвіст	',	 price:	 100.00	 	,	 category_id: 2)
 Product.create!(name:  ' Лящ чищ.патр.',	 price:		 0.00	 	,	 category_id: 2)
 Product.create!(name:  'Набір до ухи	',	 price:	 8.00	 	,	 category_id: 2)
 Product.create!(name:  ' Обрізки з лосося'	, price:		 39.75	 ,	 category_id: 2)	
 Product.create!(name:  'Піленгас стейк',	 price:		 0.00	 	,	 category_id: 2)
 Product.create!(name:  'Піленгас філе',	 price:		 0.00	 	,	 category_id: 2)
 Product.create!(name:  'Сазан стейк',	 price:		 99.90	 	,	 category_id: 2)
 Product.create!(name:  'Сом стейк	',	 price:	 169.90	 	,	 category_id: 2)
 Product.create!(name:  'Сом хвіст	'	, price:	 39.90	 ,	 category_id: 2)	
 Product.create!(name:  'Товстолоб ребро	',	 price:	 44.90	 	,	 category_id: 2)
 Product.create!(name:  'Товстолоб стейк	',	 price:	 89.90	 	,	 category_id: 2)
 Product.create!(name:  'Товстолоб філе',	 price:		 109.90	 	,	 category_id: 2)
Product.create!(name:  'Товстолоб хвіст',	 price:		 30.00	 	,	 category_id: 2)
Product.create!(name:  'Форель стейк',	 price:		 360.00	 	,	 category_id: 2)
Product.create!(name:  'Форель філе	',	 price:	 559.90	 	,	 category_id: 2)
Product.create!(name:  'Щука стейк',	 price:		 100.00	 ,	 category_id: 2)	
Product.create!(name:  'Щука філе',	 price:		0 	 	,	 category_id: 2)
Product.create!(name:  'Товстолоб стейк хвостова частина',	 price:		 49.90	 	,	 category_id: 2)
Product.create!(name:  'Молоки охолод.	',	 price:	 40.00	 	,	 category_id: 2)
Product.create!(name:  'Лосось хвіст	',	 price:	 260.00	 	,	 category_id: 2)
Product.create!(name:  'Оселедець Матьє 0,180 гр тм"Охотская"',	 price:		 23.90	 	,	 category_id: 13)
Product.create!(name:  'Икорка мойвы с коп.семгой "Водный мир"	',	 price:	 29.90	 	,	 category_id: 13)
Product.create!(name:  'Икорка мойвы с кусочк.лосос. "Водный мир"',	 price:		 29.90	 	,	 category_id: 13)
Product.create!(name:  'Мясо мидий"Водный мир"	',	 price:	 41.60	 	,	 category_id: 13)
Product.create!(name:  'Морск.кап.марин. 0,250 "С,Б."	',	 price:	 16.25	 	,	 category_id: 13)
Product.create!(name:  'Морск.кап.по-корейс. 0,250 "С,Б."	',	 price:	 18.65	 	,	 category_id: 13)
Product.create!(name:  'Морск.кап.марин.. 0,150 "С,Б."	',	 price:	 10.15	 	,	 category_id: 13)
Product.create!(name:  'Морск.кап.по-корейс. 0,150 "С,Б."	 '	, price:	11.40	 	,	 category_id: 13)
Product.create!(name:  'Ікра делік. люкс мінтая 0,130"С.Б."	'	, price:	 44.25	 	,	 category_id: 13)
Product.create!(name:  'Ікра делік. люкс тріски 0,130"С.Б."	 '	, price:	36.35	 	,	 category_id: 13)
Product.create!(name:  'Ікра №1 делік.мойви з коп.лос."С.Б"	',	 price:	 42.85	 	,category_id: 13)
Product.create!(name:  'Ікра №1 делік.мойви з кревет."С.Б"	 '	, price:	42.85	 	,category_id: 13)
Product.create!(name:  'Салат з морск.вод.Чука з імбиром "С.Б"	 '	, price:	40.10	 	,category_id: 13)
Product.create!(name:  'Салат з морск.вод.Чука з горіх.соус."С.Б."	',	 price:	 40.10	 	,category_id: 13)
Product.create!(name:  'Паста з морепрод.Антар.-Криль клас."С.Б"	'	, price:	 32.25	 	,category_id: 13)
Product.create!(name:  'Паста з морепрод.Антар.-Криль підкоп."С.Б"	'	, price:	 32.25	 	,category_id: 13)
Product.create!(name:  'Паста з мор.прод.Ант.-Криль вер.-часн.."С.Б"	',	 price:	 32.25	 	,category_id: 13)
Product.create!(name:  'Філе осел.делік. Матиас ориг. 0,250 "С.Б."	',	 price:	 52.65	 	,category_id: 13)
Product.create!(name:  'Паста ікорна Ікринка з крилем "С.Б." 0,150	 '	, price:	25.30	 	,category_id: 13)
Product.create!(name:  'Ікра делік. Люкс мінтая Pate"С.Б."0,90	'	, price:	 27.85	 	,category_id: 13)
Product.create!(name:  'Ікра делік. Люкс тріски Pate"С.Б."0,90	 '	, price:	26.55	 	,category_id: 13)
Product.create!(name:  'Бичок-тушка сол.-суш.	'	, price:	 357.00	 		,category_id: 14) 	
Product.create!(name:  'Кальмар в арахісов. олії	'	, price:	 386.40	 	,category_id: 14)
Product.create!(name:  'Кальмар кільца сол.-суш.	 '	, price:	399.00	 	,category_id: 14)
Product.create!(name:  'Кальмар стружка сол.-суш.	'	, price:	 399.00	 	,category_id: 14)
Product.create!(name:  'Лосось соломка	',	 price:	 329.00	 	,category_id: 14)
Product.create!(name:  'Соломка вобли	'	, price:	 375.00	 	,category_id: 14)
Product.create!(name:  'Стейк ляща вял.	',	 price:	 250.00	 	,category_id: 14)
Product.create!(name:  'Тунець сріблястий	 '	, price:	347.00	 	,category_id: 14)
Product.create!(name:  'Форель соломка сол.-суш.	',	 price:	 348.00	 	,category_id: 14)
Product.create!(name:  'Чіпси лосося	 ',	 price:	500.00	 	,category_id: 14)
Product.create!(name:  'Чіпси щуки	 ',	 price:	500.00	 	,category_id: 14)
Product.create!(name:  'Чіпси щуки гострі	',	 price:	 500.00	 	,category_id: 14)
 Product.create!(name:  'Янтарна з  перцем	 ',	 price:	287.00	 	,category_id: 14)
 Product.create!(name:  'Соломка щуки 	',	 price:	 450.00	 	,category_id: 14)
 Product.create!(name:  'Соломка сазана з паприкою	'	, price:	 450.00	 	,category_id: 14)
 Product.create!(name:  'Спінка тріски	'	, price:	 	0 	,category_id: 14)
 Product.create!(name:  'Солока білого амура	',	 price:	 470.00	 	,category_id: 14)
 Product.create!(name:  'Соломка тарані	',	 price:	 385.00	 	,category_id: 14)
 Product.create!(name:  'Пакет большой	'	, price:	 2.00	 	,category_id: 14)
 Product.create!(name:  'Бички вял.	'	, price:	 113.40	 	,category_id: 14)
 Product.create!(name:  'Верховодка вял.	',	 price:	 149.95	 	,category_id: 14)
 Product.create!(name:  'Вобла  вял.	',	 price:	 0.00	 	,category_id: 14)
 Product.create!(name:  'Вобла дрібна ікряна вял.	',	 price:	 0.00	 	,category_id: 14)
 Product.create!(name:  'Вобла середня ікряна вял.	',	 price:	 448.00	 	,category_id: 14)
 Product.create!(name:  'Вобла супер велика вял.	',	 price:	 700.00	 	,category_id: 14)
 Product.create!(name:  'Густера вял.	',	 price:	 0.00	 	,category_id: 14)
 Product.create!(name:  'Густера вял.чищ.	',	 price:	 74.90	 	,category_id: 14)
 Product.create!(name:  'Камбала  вял.ікряна	',	 price:	 560.00	 	,category_id: 14)
 Product.create!(name:  'Корюшка  вял. без ікри  	',	 price:	 650.00	 	,category_id: 14)
 Product.create!(name:  'Корюшка  вял.ікряна',	 price:		 750.00	 	,category_id: 14)
 Product.create!(name:  'Лящ вял.	 ',	 price:	89.60	 	,category_id: 14)
 Product.create!(name:  'Лящ вял.чищен.	',	 price:	 84.90	 	,category_id: 14)
 Product.create!(name:  'Лящ касп.ікрян. вял.	 ',	 price:	168.00	 	,category_id: 14)
 Product.create!(name:  'Окунь  вял.	',	 price:	 109.20	 	,category_id: 14)
 Product.create!(name:  'Плотва вял.',	 price:		 0.00	 	,category_id: 14)
 Product.create!(name:  'Плотва вял.чищен.	'	, price:	 74.90	 	,category_id: 14)
 Product.create!(name:  'Плотва вял.чищен.ікряна	',	 price:	 149.90	 	,category_id: 14)
 Product.create!(name:  'Судак вял.	',	 price:	 182.40	 	,category_id: 14)
 Product.create!(name:  'Тарань вял ікряна	'	, price:	 0.00	 	,category_id: 14)
 Product.create!(name:  'Тарань вял.чищена	',	 price:	 149.00	 	,category_id: 14)
 Product.create!(name:  'Тарань вял.чищена ікряна'	, price:		 299.00	 ,category_id: 14) 	
 Product.create!(name:  'Чехонь вял.	',	 price:	 0.00	 	,category_id: 14)
 Product.create!(name:  'Щука вял.	',	 price:	 0.00	 	,category_id: 14)
 Product.create!(name:  'Щука вял. Касп.'	, price:		 420.00	 	,category_id: 14) 
 Product.create!(name:  'Лящ вял.чищ з ікр.'	, price:		 150.00	 	,category_id: 14)
 	 	 	 	
 	 	 	 	
 	 	 	 	
 Product.create!(name:  'Бички великі	',	 price:	 25.00	 	, 	category_id: 2) 
 Product.create!(name:  ' Бички дрібні	'	, price:	 21.84	 	, 	category_id: 2) 
 Product.create!(name:  'Блувайтінг	',	 price:	 60.30	 	, 	category_id: 2) 
 Product.create!(name:  ' Восьминоги бебі	',	 price:	 0.00	 	, 	category_id: 2) 
 Product.create!(name:  ' Камбала дволінійна	',	 price:	 85.54	 	, 	category_id: 2) 
 Product.create!(name:  'Килька	',	 price:	 19.90	 	, 	category_id: 2) 
 Product.create!(name:  'Кінг-кліп	',	 price:	 143.00	 	, 	category_id: 2) 
 Product.create!(name:  'Крабові палички 	',	 price:	 0.00	 	, 	category_id: 2) 
 Product.create!(name:  'Крабові палички 0,240 г',	 price:		 29.00	 , 	category_id: 2) 	
 Product.create!(name:  'Крабові палички 0,500 г',	 price:		 54.30	 , 	category_id: 2) 	
 Product.create!(name:  'Крабовые палочки(вес)	'	, price:	 109.20	 , 	category_id: 2) 	
 Product.create!(name:  'Масляна стейк	'	, price:	 0.00	, 	category_id: 2) 	
 Product.create!(name:  'Минтай тушка	 '	, price:	69.94	 , 	category_id: 2)	
 Product.create!(name:  'Мідії	',	 price:	 0.00	 	, 	category_id: 2)
 Product.create!(name:  'Мойва	',	 price:	 56.94	 	, 	category_id: 2)
 Product.create!(name:  'Морской коктейль	',	 price:	 117.00	 	, 	category_id: 2)
 Product.create!(name:  'Мясо камбали	',	 price:	 0.00	 	, 	category_id: 2)
 Product.create!(name:  'Натотенія тушка	',	 price:	 61.50	 	, 	category_id: 2)
 Product.create!(name:  'Обрізки лосося',	 price:		 0.00	 	, 	category_id: 2)
 Product.create!(name:  'Окунь червоний тушка'	, price:		 149.50	 	, 	category_id: 2)
 Product.create!(name:  'Салака с/м	', price:	28.35	 	, 	category_id: 2)
 Product.create!(name:  'Скумбрія б/г	',	 price:	0.00	 	, 	category_id: 2)
 Product.create!(name:  'Скумбрія з/г	'	, price:	69.30	 	, 	category_id: 2)
 Product.create!(name:  'Стейк зубатки'	, price:	 59.80	 	, 	category_id: 2)
 Product.create!(name:  'Тріска червона б/г',	 price:		 85.54	 , 	category_id: 2)	
 Product.create!(name:  'Тунець(жовсохвіст)',	 price:	77.10	 	, 	category_id: 2)
 Product.create!(name:  'Фарш лосося(туби)'	, price:	 0.00	 	, 	category_id: 2)
 Product.create!(name:  'Фарш хека (туби)',	 price:	 0.00	 	, 	category_id: 2)
 Product.create!(name:  'Филе хека з/ш',	 price:	74.49	 	, 	category_id: 2)
 Product.create!(name:  'Філе гольца',	 price:	 0.00	 	, 	category_id: 2)
 Product.create!(name:  'Філе мінтая',	 price:	65.39	 	, 	category_id: 2)
 Product.create!(name:  'Філе пангасіуса'	, price:	77.74	 	, 	category_id: 2)
 Product.create!(name:  'Філе тілапії',	 price:	119.34	 	, 	category_id: 2)
 Product.create!(name:  ' Хек тушка Канада'	, price:	64.10	 	, 	category_id: 2)
 Product.create!(name:  'Хек тушка Аргентина',	 price:	 0.00	 	, 	category_id: 2)
 Product.create!(name:  'Пангасиус -тушка',	 price:	77.74	 	, 	category_id: 2)
 Product.create!(name:  'Хек тушка Аргентина ( акція)	'	, price:	 64.90	 , 	category_id: 2)	
 Product.create!(name:  'Горбуша-тушка	 '	, price:	182.00	 	, 	category_id: 2)
 Product.create!(name:  'Гренадер тушка б/ш( акція)	',	 price:	 50.00	 , 	category_id: 2)	
 Product.create!(name:  'Морський кролик(акула-тушка)	'	, price:	 92.30, 	category_id: 2) 	
 Product.create!(name:  'Барабулька с/м	',	 price:	 100.00	, 	category_id: 2)
 Product.create!(name:  ' Креветка 70-90 Гренландія ',	 price:		 297.00	 		 ,	 category_id: 13)
 Product.create!(name:  'Креветка 90-120	',	 price:	 249.75	 		 ,	 category_id: 13)
 Product.create!(name:  'Креветка чорноморська	'	, price:	 180.00	 		 ,	 category_id: 13)
 Product.create!(name:  'Бычки Аквамарин в т/с	'	, price:	 21.10		 ,	 category_id: 13) 	
 Product.create!(name:  'Килька Аквамарин  в т/с	'	, price:	 10.90	 	 ,	 category_id: 13)	
 Product.create!(name:  'Мясо криля Аквамарин нат.	'	, price:	 62.40	 	 ,	 category_id: 13)	
 Product.create!(name:  'Печень трески Аквамарин нат	'	, price:	 42.10	 		 ,	 category_id: 13)
 Product.create!(name:  'Печень трески Аквамарин нат ключ	'	, price:	 62.35	 	 ,	 category_id: 13)	
 Product.create!(name:  'Сайра Аквамарин натур.0,230 г	',	 price:	 36.85	 		 ,	 category_id: 13)
 Product.create!(name:  'Сардина Аквамарин НДО	',	 price:	 25.00	 		 ,	 category_id: 13)
 Product.create!(name:  'Тунец для салатов Аквамарин в с/с	'	, price:	 40.55	 		 ,	 category_id: 13)
 Product.create!(name:  'Тунец для салатов Аквамарин в/м ключ	',	 price:	 40.55	 		 ,	 category_id: 13)
 Product.create!(name:  'Шпроты Аквамарин в/м 0,150 г	'	, price:	 24.95	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва Br.villnisкилька',	 price:		 40.60	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва Br.villnis печень трески	',	 price:	 50.25	 	 ,	 category_id: 13)	
 Product.create!(name:  'Консерва Br.villnis шпроты 0,160',	 price:		 41.75	 	 ,	 category_id: 13)	
 Product.create!(name:  'Консерва Br.villnis шпроты 0,190',	 price:		 54.05	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва тунец Рио в масле	',	 price:	 40.00	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва тунец Рио в с/с	',	 price:	 40.00	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва РЗ шпроты 0,240	',	 price:	 48.00	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва РЗ шпроты 0,160	',	 price:	 37.75	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва РЗ паштет шпротный	',	 price:	 15.50	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва печ треск.Baltik Sea	',	 price:	 72.60	 		 ,	 category_id: 13)
 Product.create!(name:  'Килька в т/с Вентспилс	'	 ,price:	 24.50	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва Сардина в/м Вентспилс	 '	, price:	30.00	 	 ,	 category_id: 13)	
 Product.create!(name:  'Консерва Скумбрия в/м Вентспилс	',	 price:	 33.50	 	 ,	 category_id: 13)	
 Product.create!(name:  'Консерва бычки обж.в том. Соусе	'	, price:	 15.40	 	 ,	 category_id: 13)	
 Product.create!(name:  'Консерва икра"Спец.посол"	 '	, price:	215.00	 		 ,	 category_id: 13)
 Product.create!(name:  'Консерва икра "Камчадал"	',	 price:	 247.00	 		 ,	 category_id: 13)
 Product.create!(name:  'Оселедець Матьє 0,180 гр тм"Охотская"	',	 price:	 23.90	 		 ,	 category_id: 13)
 Product.create!(name:  'Икорка мойвы с коп.семгой "Водный мир"	 ',	 price:	29.90	 		 ,	 category_id: 13)
 Product.create!(name:  'Икорка мойвы с кусочк.лосос. "Водный мир"	',	 price:	 29.90	 	 ,	 category_id: 13)	
 Product.create!(name:  'Мясо мидий"Водный мир"	 ',	 price:	41.60		 ,	 category_id: 13) 	
